create table users(
      username varchar(50) not null primary key,
      password varchar(50) not null,
      enabled boolean not null);

  create table authorities (
      username varchar(50) not null,
      authority varchar(50) not null,
      constraint fk_authorities_users foreign key(username) references users(username));
      create unique index ix_auth_username on authorities (username,authority);

create table productcategory
(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) not null primary key,
	category_name VARCHAR(256),
	category_id BIGINT
)